#Brian Aguirre
#ba5bx
#Makefile

#ORIGINAL MAKE FILE USED FROM PREVIOUS LAB
#PROVIDED BY AARON BLOOMFIELD

#DEFINES WHICH COMPILER WE'LL BE USING
CXX	= clang++ 

#DEFINES ANY FLAGS PASSING TO C++ COMPILER
CXXFLAGS	= -Wall -g


.SUFFIXES: .o .cpp

main:	topological.cpp
	$(CXX) topological.cpp


#CLEANUP
clean:
	/bin/rm -f *.o *~


